name: Deploy Laravel to FTP

# Запускать робота при отправке кода в любую из главных веток
on:
  push:
    branches:
      - main
      - master

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Получение свежего кода
        uses: actions/checkout@v4

      - name: ⚙️ Установка PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: 📦 Установка библиотек (Composer)
        run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction

      - name: 🚀 Загрузка файлов на хостинг по FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Указываем твою папку на хостинге
          server-dir: ./http/
          # Исключаем системные файлы
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env.example
            README.md
